=begin
#Content API

#Content API for KIQR Headless CMS

The version of the OpenAPI document: 0.16.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kiqr::ContentApi::RelationshipsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RelationshipsApi' do
  before do
    # run before each test
    @api_instance = Kiqr::ContentApi::RelationshipsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RelationshipsApi' do
    it 'should create an instance of RelationshipsApi' do
      expect(@api_instance).to be_instance_of(Kiqr::ContentApi::RelationshipsApi)
    end
  end

  # unit tests for get_relations
  # Returns a list of related documents
  # @param content_type_id 
  # @param document_id 
  # @param field_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentsCollection]
  describe 'get_relations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
