=begin
#Content API

#Content API for KIQR Headless CMS

The version of the OpenAPI document: 0.5.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KIQR::DocumentsCollectionMeta
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KIQR::DocumentsCollectionMeta do
  let(:instance) { KIQR::DocumentsCollectionMeta.new }

  describe 'test an instance of DocumentsCollectionMeta' do
    it 'should create an instance of DocumentsCollectionMeta' do
      expect(instance).to be_instance_of(KIQR::DocumentsCollectionMeta)
    end
  end
  describe 'test attribute "pagination"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
