=begin
#Content API

#Content API for KIQR Headless CMS

The version of the OpenAPI document: 0.6.3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

module Kiqr::ContentApi
  VERSION = '1.0.0'
end
