=begin
#Content API

#Content API for KIQR Headless CMS

The version of the OpenAPI document: 0.5.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

module KIQR
  VERSION = '1.0.0'
end
