=begin
#Content API

#Content API for KIQR Headless CMS

The version of the OpenAPI document: 0.5.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

# Common files
require 'kiqr-content-api/api_client'
require 'kiqr-content-api/api_error'
require 'kiqr-content-api/version'
require 'kiqr-content-api/configuration'

# Models
KIQR.autoload :Document, 'kiqr-content-api/models/document'
KIQR.autoload :DocumentsCollection, 'kiqr-content-api/models/documents_collection'
KIQR.autoload :DocumentsCollectionMeta, 'kiqr-content-api/models/documents_collection_meta'
KIQR.autoload :PaginationMeta, 'kiqr-content-api/models/pagination_meta'

# APIs
KIQR.autoload :DocumentsApi, 'kiqr-content-api/api/documents_api'

module KIQR
  class << self
    # Customize default settings for the SDK using block.
    #   KIQR.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
